### ISSUE TITLE
Alias for switch command stop working after restart

### ISSUE THREAD

**Issue by Eldhrimer** [the-lay/ulauncher-spotify-api#15] opened 2021-01-30 21:12 UTC
I use the switch command a lot, so I made an alias for it, following the instructions in the extension's settings and being careful about spaces. After logging out and in again, or when restarting the launcher, the extension stops reading my alias for that specific command. Artist and Album aliases work as expected.

This is my aliases string 
s: search; song: track; art: artist; on: switch; alb: albums

**Comment by the-lay** [comment] 2021-02-01 15:59
Thanks for the bugreport! I can confirm, I have the same problem. It seems the problem is with setting alias string in general, not specifically switch command. I will try to fix it today.

**Comment by the-lay** [comment] 2021-02-01 16:19
Turns out it was a tiny dumb problem and it should be fixed now. Please update the extension and try again!

**Comment by Eldhrimer** [comment] 2021-02-01 20:42
Perfect! thanks for the quick fix!

**Closed** 2021-02-01 21:23 UTC
Labels: bug
